package siprec

import (
	"sync"
)

// ========================================================================
// SIPREC Session Tracker — Dialog State + Port→CallID Mapping
// Enables port recycling on BYE and re-INVITE SDP updates.
// ========================================================================

// DialogState represents the state of a SIP dialog.
type DialogState int

const (
	DialogTrying    DialogState = iota // INVITE received, 100 Trying sent
	DialogConfirmed                    // 200 OK sent, dialog established
)

// Session holds the state of a SIPREC recording session.
type Session struct {
	mu        sync.Mutex // R-7: protects field mutations after creation
	CallID    string
	Ports     []int  // RTP ports allocated for this session
	RemoteTag string // From-tag of the remote party
	LocalTag  string // To-tag generated by us
	State     DialogState
}

// SessionTracker manages active SIPREC sessions.
// Thread-safe via sync.Map for lock-free reads on hot path.
type SessionTracker struct {
	sessions sync.Map // callID → *Session
}

// NewSessionTracker creates a new session tracker.
func NewSessionTracker() *SessionTracker {
	return &SessionTracker{}
}

// StorePending creates a new session in Trying state (before SDP processing).
func (st *SessionTracker) StorePending(callID string) {
	st.sessions.Store(callID, &Session{
		CallID: callID,
		State:  DialogTrying,
	})
}

// Confirm transitions a session to Confirmed state with allocated ports.
func (st *SessionTracker) Confirm(callID string, ports []int, localTag string) {
	val, ok := st.sessions.Load(callID)
	if ok {
		sess := val.(*Session)
		sess.mu.Lock()
		sess.Ports = ports
		sess.LocalTag = localTag
		sess.State = DialogConfirmed
		sess.mu.Unlock()
	} else {
		// Store directly if no pending entry
		st.sessions.Store(callID, &Session{
			CallID:   callID,
			Ports:    ports,
			LocalTag: localTag,
			State:    DialogConfirmed,
		})
	}
}

// Store creates or overwrites a session in Confirmed state.
func (st *SessionTracker) Store(callID string, ports []int, remoteTag string) {
	st.sessions.Store(callID, &Session{
		CallID:    callID,
		Ports:     ports,
		RemoteTag: remoteTag,
		State:     DialogConfirmed,
	})
}

// Get retrieves a session by callID.
func (st *SessionTracker) Get(callID string) (*Session, bool) {
	val, ok := st.sessions.Load(callID)
	if !ok {
		return nil, false
	}
	return val.(*Session), true
}

// GetPorts returns a copy of the RTP ports for a session, or empty slice if not found.
// Thread-safe: acquires sess.mu to prevent races with UpdatePorts.
func (st *SessionTracker) GetPorts(callID string) []int {
	sess, ok := st.Get(callID)
	if !ok {
		return nil
	}
	sess.mu.Lock()
	defer sess.mu.Unlock()
	cp := make([]int, len(sess.Ports))
	copy(cp, sess.Ports)
	return cp
}

// UpdatePorts replaces the ports for a session (used on re-INVITE).
func (st *SessionTracker) UpdatePorts(callID string, newPorts []int) {
	if val, ok := st.sessions.Load(callID); ok {
		sess := val.(*Session)
		sess.mu.Lock()
		sess.Ports = newPorts
		sess.mu.Unlock()
	}
}

// Delete removes a session (called on BYE).
func (st *SessionTracker) Delete(callID string) {
	st.sessions.Delete(callID)
}

// ActiveCount returns the number of active sessions.
func (st *SessionTracker) ActiveCount() int {
	count := 0
	st.sessions.Range(func(_, _ interface{}) bool {
		count++
		return true
	})
	return count
}
