// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ser.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	AudioData     []byte                 `protobuf:"bytes,2,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"` // Float32 little-endian PCM data
	SampleRate    int32                  `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_ser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_ser_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *AnalyzeRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *AnalyzeRequest) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type EmotionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emotion       string                 `protobuf:"bytes,1,opt,name=emotion,proto3" json:"emotion,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Arousal       float32                `protobuf:"fixed32,3,opt,name=arousal,proto3" json:"arousal,omitempty"`
	Valence       float32                `protobuf:"fixed32,4,opt,name=valence,proto3" json:"valence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmotionResult) Reset() {
	*x = EmotionResult{}
	mi := &file_ser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmotionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmotionResult) ProtoMessage() {}

func (x *EmotionResult) ProtoReflect() protoreflect.Message {
	mi := &file_ser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmotionResult.ProtoReflect.Descriptor instead.
func (*EmotionResult) Descriptor() ([]byte, []int) {
	return file_ser_proto_rawDescGZIP(), []int{1}
}

func (x *EmotionResult) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *EmotionResult) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *EmotionResult) GetArousal() float32 {
	if x != nil {
		return x.Arousal
	}
	return 0
}

func (x *EmotionResult) GetValence() float32 {
	if x != nil {
		return x.Valence
	}
	return 0
}

type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emotions      []*EmotionResult       `protobuf:"bytes,1,rep,name=emotions,proto3" json:"emotions,omitempty"`
	Dominant      string                 `protobuf:"bytes,2,opt,name=dominant,proto3" json:"dominant,omitempty"`
	AvgArousal    float32                `protobuf:"fixed32,3,opt,name=avg_arousal,json=avgArousal,proto3" json:"avg_arousal,omitempty"`
	AvgValence    float32                `protobuf:"fixed32,4,opt,name=avg_valence,json=avgValence,proto3" json:"avg_valence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_ser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_ser_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeResponse) GetEmotions() []*EmotionResult {
	if x != nil {
		return x.Emotions
	}
	return nil
}

func (x *AnalyzeResponse) GetDominant() string {
	if x != nil {
		return x.Dominant
	}
	return ""
}

func (x *AnalyzeResponse) GetAvgArousal() float32 {
	if x != nil {
		return x.AvgArousal
	}
	return 0
}

func (x *AnalyzeResponse) GetAvgValence() float32 {
	if x != nil {
		return x.AvgValence
	}
	return 0
}

var File_ser_proto protoreflect.FileDescriptor

const file_ser_proto_rawDesc = "" +
	"\n" +
	"\tser.proto\x12\x03ser\"i\n" +
	"\x0eAnalyzeRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x02 \x01(\fR\taudioData\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\x05R\n" +
	"sampleRate\"}\n" +
	"\rEmotionResult\x12\x18\n" +
	"\aemotion\x18\x01 \x01(\tR\aemotion\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x18\n" +
	"\aarousal\x18\x03 \x01(\x02R\aarousal\x12\x18\n" +
	"\avalence\x18\x04 \x01(\x02R\avalence\"\x9f\x01\n" +
	"\x0fAnalyzeResponse\x12.\n" +
	"\bemotions\x18\x01 \x03(\v2\x12.ser.EmotionResultR\bemotions\x12\x1a\n" +
	"\bdominant\x18\x02 \x01(\tR\bdominant\x12\x1f\n" +
	"\vavg_arousal\x18\x03 \x01(\x02R\n" +
	"avgArousal\x12\x1f\n" +
	"\vavg_valence\x18\x04 \x01(\x02R\n" +
	"avgValence2J\n" +
	"\x10EmissionAnalyzer\x126\n" +
	"\aAnalyze\x12\x13.ser.AnalyzeRequest\x1a\x14.ser.AnalyzeResponse\"\x00B0Z.github.com/cxmind/ingestion-go/internal/ser/pbb\x06proto3"

var (
	file_ser_proto_rawDescOnce sync.Once
	file_ser_proto_rawDescData []byte
)

func file_ser_proto_rawDescGZIP() []byte {
	file_ser_proto_rawDescOnce.Do(func() {
		file_ser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ser_proto_rawDesc), len(file_ser_proto_rawDesc)))
	})
	return file_ser_proto_rawDescData
}

var file_ser_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ser_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),  // 0: ser.AnalyzeRequest
	(*EmotionResult)(nil),   // 1: ser.EmotionResult
	(*AnalyzeResponse)(nil), // 2: ser.AnalyzeResponse
}
var file_ser_proto_depIdxs = []int32{
	1, // 0: ser.AnalyzeResponse.emotions:type_name -> ser.EmotionResult
	0, // 1: ser.EmissionAnalyzer.Analyze:input_type -> ser.AnalyzeRequest
	2, // 2: ser.EmissionAnalyzer.Analyze:output_type -> ser.AnalyzeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ser_proto_init() }
func file_ser_proto_init() {
	if File_ser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ser_proto_rawDesc), len(file_ser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ser_proto_goTypes,
		DependencyIndexes: file_ser_proto_depIdxs,
		MessageInfos:      file_ser_proto_msgTypes,
	}.Build()
	File_ser_proto = out.File
	file_ser_proto_goTypes = nil
	file_ser_proto_depIdxs = nil
}
